{"name": "test_login_with_missing_fields", "status": "failed", "statusDetails": {"message": "AssertionError: Не возвращается ошибка при отсутствии поля\nassert 504 == 400\n +  where 504 = <Response [504]>.status_code", "trace": "self = <test_courier_login.TestCourierLogin object at 0x000001636CD26950>\n\n    def test_login_with_missing_fields(self):\n        response = requests.post('https://qa-scooter.praktikum-services.ru/api/v1/courier/login',\n                                 data={\"login\": self.new_courier[\"login\"]})\n>       assert response.status_code == 400, \"Не возвращается ошибка при отсутствии поля\"\nE       AssertionError: Не возвращается ошибка при отсутствии поля\nE       assert 504 == 400\nE        +  where 504 = <Response [504]>.status_code\n\ntests\\test_courier_login.py:28: AssertionError"}, "start": 1727633907238, "stop": 1727633967378, "uuid": "08fc60c4-03de-4980-9ec3-0bf654a9fc35", "historyId": "261b647b0e6f7dd4131761815e813589", "testCaseId": "261b647b0e6f7dd4131761815e813589", "fullName": "tests.test_courier_login.TestCourierLogin#test_login_with_missing_fields", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "Kurbakov"}, {"name": "thread", "value": "96276-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}